#!/bin/sh
sed -e \
's/CITROEN ELEKTRIQUE/CITROEN/' -e 's/CITROEN -/CITROEN/' -e 's/CITROEN BER.*$/CITROEN BERLINGO/' -e 's/CITROEN BER.*;/CITROEN BERLINGO/' -e 's/CITROEN.*SAXO.*(;\|$)/CITROEN SAXO/' -e \
's/FIAT FIAT/FIAT/' -e 's/FIAT.*500.*(;\|$)/FIAT 500/' -e \
's/FORD-CNG-TECHNIK/FORD/' -e 's/FORD FOCU.*($|;)/FORD FOCUS/i' -e \
's/KEWET.*(;\|$)/KEWET/' -e \
's/MAN.*TROLLEY BUSS.*(;\|$)/MAN TROLLEY BUSS/' -e \
's/MIA MIA/MIA/' -e 's/MIA ELE.?TRIQUE/MIA/' -e 's/MIA ELECTRIC/MIA/' -e 's/MIA -/MIA/' -e \
's/MITSUBISHI MITSUBISHI/MITSUBISHI/' -e \
's/NISSAN -/NISSAN/' -e 's/NISSAN NISSAN/NISSAN/' -e 's/NISSA.*LEAF.*(;|$)/NISSAN LEAF/' -e \
's/PEUGEOT PEUGEOT/PEUGEOT/' -e 's/PEUGEOT ELECTRIQUE/PEUGEOT/' -e 's/PEUGEOT -/PEUGEOT/' -e 's/PEUGEOT ELECTRIC/PEUGEOT/' -e \
's/PEUGEOT 1?06.*(;\|$)/PEUGEOT 106/' -e 's/PEUGEOT PARTNER.*(;\|$)/PEUGEOT PARTNER/' -e 's/PEUGEOT.*I.?N.*(;\|$)/PEUGEOT ION/' -e \
's/PIAGGIO.*PORTER.*(;\|$)/PIAGGIO PORTER/' -e \
's/RENAULT RENAULT/RENAULT/' -e 's/RENAULT -/RENAULT/' -e 's/RENAULT KANGO.*(;\|$)/RENAULT KANGOO;/' -e 's/RENAULT CLIO.*(;\|$)/RENAULT CLIO/' -e 's/RENAULT CL10.*(;\|$)/RENAULT CLIO/' -e \
's/EXPRESS Z.E\./EXPRESS Z.E/' -e \
's/SMART.*FORTWO.*(;\|$)/SMART FORTWO/' -e 's/SMART ELECTRIC DRIVE/SMART/' -e 's/SMART SMART/SMART/' -e \
's/THINK.*CITY.*(;\|$)/THINK CITY/' -e 's/THINK.*PIV.*4.*/THINK CITY/' -e 's/THINK A306/THINK CITY/' -e 's/THINK THINK/THINK/' -e \
's/TESLA MOTORS PERFORMANCE/TESLA MODEL S/' -e 's/TESLA TESLA/TESLA/' -e 's/TESLA MOTORS/TESLA/' -e 's/TESLA ROAD.*(;\|$)/TESLA ROADSTER/' -e 's/MODEL S PERFORMANCE/MODEL S/' -e \
's/TOYOTA RAV.*(;\|$)/TOYOTA RAV4/' -e \
's/VOLKSWAGEN.*CIT.? ?S.*(;\|$)/VOLKSWAGEN GOLF CITYSTROMER/' -e 's/VOLKSWAGEN UP(;\|$)/VOLKSWAGEN UP\!/' -e \
's/ GRØNN//'
